### PR TITLE
Added start parameter to predict.flexsurvreg

### LINKED ISSUE #97: Add start argument to predict.flexsurvreg method
Hi @chjackson,

Do you think the `start` argument should be added to the `predict.flexsurvreg` method (and passed on to `summary.flexsurvreg`, which actually does the work)?

I don't recall if there was a reason we omitted this argument when creating the predict method. I would be happy to contribute the PR if you want this addition.

As a side note for my understanding, is there a reason why the `times` argument is ignored for predictions of `type = "link"` and predictions are made at time = 0 only?

### PR DESCRIPTION
**Pull request by mattwarkentin**
Closes #97

### CODE REVIEW

**Comment by chjackson** [comment]
Thanks!  (I should switch off the travis checks or find out why they are not working)

**Comment by mattwarkentin** [comment]
If you're ever interested in migrating your testing over to GitHub Actions, I would be happy to help with that. I have set this up for many of my own R packages. It's quite nice and removes the need to rely on external services like Travis.

**Comment by chjackson** [comment]
Thank you @mattwarkentin - very happy for you to set up this migration for flexsurv.

**Comment by mattwarkentin** [comment]
See #99

**Pull request merged**
